import React, { useState, useEffect, useCallback } from 'react';
import { DoctorAPI } from '../services/api';
import Toast from '../components/Toast';
const SP=['Cardiology','Neurology','Orthopedics','Dermatology','Pediatrics','Oncology','General Medicine','Psychiatry','Radiology','Emergency Medicine','Gynecology','Urology','ENT','Ophthalmology','Dentistry'];
function DoctorModal({onSave,onClose}){
  const [form,setForm]=useState({dName:'',dSpeciality:'',dExperience:'',dContact:''});
  const set=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
  const submit=e=>{e.preventDefault();onSave({dName:form.dName,dSpeciality:form.dSpeciality,dExperience:parseInt(form.dExperience),dContact:form.dContact});};
  return(<div className="overlay" onClick={e=>e.target.className==='overlay'&&onClose()}><div className="modal"><div className="modal-title">Add New Doctor</div><form onSubmit={submit}><div className="form-group"><label className="form-label">Full Name (dName)</label><input className="form-input" name="dName" value={form.dName} onChange={set} placeholder="Dr. Name" required/></div><div className="form-group"><label className="form-label">Speciality (dSpeciality)</label><select className="form-select" name="dSpeciality" value={form.dSpeciality} onChange={set} required><option value="">-- Select --</option>{SP.map(s=><option key={s}>{s}</option>)}</select></div><div className="form-row"><div className="form-group"><label className="form-label">Experience (yrs)</label><input className="form-input" name="dExperience" type="number" value={form.dExperience} onChange={set} placeholder="e.g. 10" min="0" required/></div><div className="form-group"><label className="form-label">Contact (dContact)</label><input className="form-input" name="dContact" value={form.dContact} onChange={set} placeholder="Phone/email" required/></div></div><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button><button type="submit" className="btn btn-primary">Save Doctor</button></div></form></div></div>);
}
export default function Doctors(){
  const [doctors,setDoctors]=useState([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(false);const [toast,setToast]=useState(null);
  const load=useCallback(()=>{setLoading(true);DoctorAPI.getAll().then(r=>setDoctors(Array.isArray(r.data)?r.data:[])).catch(()=>setToast({message:'Failed to load',type:'error'})).finally(()=>setLoading(false));},[]);
  useEffect(()=>{load();},[load]);
  const handleSave=d=>DoctorAPI.create(d).then(()=>{setModal(false);setToast({message:'Doctor added!',type:'ok'});load();}).catch(()=>setToast({message:'Failed',type:'error'}));
  const handleDelete=id=>{if(!window.confirm('Delete?'))return;DoctorAPI.delete(id).then(()=>{setToast({message:'Deleted',type:'ok'});load();}).catch(()=>setToast({message:'Failed',type:'error'}));};
  return(<div>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}{modal&&<DoctorModal onSave={handleSave} onClose={()=>setModal(false)}/>}<div className="section-header"><div className="section-title">All Doctors</div><button className="btn btn-primary" onClick={()=>setModal(true)}>+ Add Doctor</button></div>{loading?<div className="loading"><div className="spinner"/>Loading...</div>:doctors.length===0?<div className="empty"><div className="empty-icon">🩺</div><h3>No doctors yet</h3><p>Click "Add Doctor" to get started.</p></div>:(<div className="cards-grid">{doctors.map(d=>(<div className="card card-purple" key={d.dId}><div className="card-head"><div><div className="card-id">Doctor #{d.dId}</div><div className="card-name">{d.dName}</div></div><span className="badge b-purple">{d.dSpeciality}</span></div><div className="card-fields"><div className="field"><span className="field-key">dName</span><span className="field-val">{d.dName}</span></div><div className="field"><span className="field-key">dSpeciality</span><span className="field-val">{d.dSpeciality}</span></div><div className="field"><span className="field-key">dExperience</span><span className="field-val">{d.dExperience} years</span></div><div className="field"><span className="field-key">dContact</span><span className="field-val">{d.dContact}</span></div></div><div className="card-footer"><button className="btn btn-danger btn-sm" onClick={()=>handleDelete(d.dId)}>🗑 Delete</button></div></div>))}</div>)}</div>);
}
